### ISSUE TITLE
On 23.1.x enable intel xe drivers

### ISSUE THREAD

**Issue by Quackdoc** [waydroid/android_external_mesa3d#7]
enable `-Dintel-xe-kmd=enabled` when mesa is bumped to 23.1.x will allow running on the new xe driver instead of i915, this allegedly has better vulkan preformance, but mainly people are starting to use it and swapping from I915 to XE is probably not something a user wants to do

**Comment by kode54** [comment]
Just a note, it doesn't replace i915 support. Both Iris and ANV support both drivers, and all of the merged code going into 23.1.x there supports both at compile time regardless of the flag. The compile time flag currently only allows it to detect and enable the support.

I'll be tracking this, thanks.

**Comment by aleasto** [comment]
Do you know why this is a compile time option? Not like the kernel is going to expose both DRM drivers...

**Comment by aleasto** [comment]
Done.
But you'll get whatever support there is in mesa-23.1, which is probably close to none
